SCREEN_WIDTH, SCREEN_HEIGHT = love.graphics.getDimensions()

DEBUG_VIEW = true

DT = 1/30

FPS = 0
FPS_TIMER = 0
FPS_COUNTER = 0

DEFAULT_GENERAL_MEMORY_SPEED = 50
GENERAL_MEMORY_SPEED = DEFAULT_GENERAL_MEMORY_SPEED

DEFAULT_MEMORY_SPAWN_RATE = 5
MEMORY_SPAWN_RATE = DEFAULT_MEMORY_SPAWN_RATE

MEMORY_SCALE = 0.5